version: 2.1
jobs:
  test:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: prod
    working_directory: ~/harald/src
    steps:
      - checkout:
          path: ~/harald
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix clean --deps
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: MIX_ENV=test mix test
      - run: mix format --check-formatted
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - _build
      - save_cache:
          key: v1-{{ epoch }}
          paths:
            - _build
  coveralls_report:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: test
    working_directory: ~/harald/src
    steps:
      - checkout:
          path: ~/harald
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix clean --deps
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: MIX_ENV=test mix coveralls.circle
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - coveralls_report:
          filters:
            branches:
              only: master
